#!/bin/bash

# compiled files
#files="kinds.f90 command_line.f90 nearrup.f90"
files="kinds.f90 command_line.f90 create_axis.f90 potential.f90 pot_driver.f90"

# output file
ofile="pot_driver"

# flags
fflags="-Wall -Wextra -std=f2003 -O3"

# compile
gfortran $fflags $files -o $ofile

# run
./$ofile nx=50 ny=50 problem=null

# show results
#python3 visualise.py -fname1 sim.txt -fname2 rup.txt
