#!/bin/bash

# compiled files
files="kinds.f90 command_line.f90 create_axis.f90 potential.f90 verlet.f90 re_writenetcdf.f90 program_code.f90"

# output file
ofile="main_program"

# compiler
fc=gfortran

# flags
fflags=`nf-config --fflags`
flibs=`nf-config --flibs`

# compile
$fc -g -std=f2003 -Wall $fflags $files $flibs -o $ofile

# run
./$ofile nx=100 ny=100 problem=double

# visualise results
#python3 pseudoplot.py
#python3 scatter.py
