#!/bin/bash

# compiled files
files="kinds.f90 command_line.f90 create_axis.f90 potential.f90 \
 verlet.f90 program_code.f90"

# output file
ofile="prog"

# flags
fflags="-Wall -Wextra -std=f2003 -O3"

# compile
gfortran $fflags $files -o $ofile

# run
./$ofile nx=5 ny=5 problem=single

# visualise results
